#This workflow sends email based on events

name: Send email on issue update

on:
  push:
    branches:
      - master
      - main
  issues:
    types: [opened, labeled, closed]
  issue_comment:
    types: [created]
  release:
    types: [ published ]

jobs:
  push_trigger:
    name: Send email on push
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    env: 
      GITHUB_CONTEXT : ${{ toJson(github) }}
    steps:
      - run: echo "$GITHUB_CONTEXT"
  issue_opened:
    name: Send email on issue opened
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: github push event
          to: ${{secrets.RECIPIENT_EMAIL}}
          from: Github actions bot
          body: "((issue opened: Issue ${{github.event.issue.number}} ${{github.event.issue.title}}. For more information: github.com/${{github.repository}}/${{github.event.issue.number}}/))"
  issue_comment:
    name: Send email on comment in issue
    if: ${{github.event_name == 'issue_comment'}}
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: github push event
          to: ${{secrets.RECIPIENT_EMAIL}}
          from: Github actions bot
          body: "((New comment on Issue ${{github.event.issue.number}} ${{github.event.issue.title}} comment: ${{github.event.comment.body}}. For more information: github.com/${{github.repository}}/${{github.event.issue.number}}/))" 
          
  issue_closed:
    name: Send email on issue closed
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: github push event
          to: ${{secrets.RECIPIENT_EMAIL}}
          from: Github actions bot
          body: "((issue closed: Issue ${{github.event.issue.number}} ${{github.event.issue.title}}.  For more information: github.com/${{github.repository}}/${{github.event.issue.number}}/ ))" 
          
  label_trigger:
    name: Send email on issue labelled
    if: ${{github.event.action == 'labeled' }}
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: github push event
          to: ${{secrets.RECIPIENT_EMAIL}}
          from: Github actions bot
          body: "((issue labelled: Issue ${{github.event.issue.number}} ${{github.event.issue.title}} is now labelled as ${{github.event.label.name}}. For more information: github.com/${{github.repository}}/${{github.event.issue.number}}/))"
  
  release_trigger:
    name: Send email on new release
    if: ${{github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: github push event
          to: ${{secrets.RECIPIENT_EMAIL}}
          from: Github actions bot
          body: "((A new version is available: ${{github.event.release.tag_name}}))"

  
 # get_github_context:
 #   name: get github context
 #   runs-on: ubuntu-latest
 #   env: 
 #     GITHUB_CONTEXT : ${{ toJson(github) }}
 #   steps:
 #     - run: echo "$GITHUB_CONTEXT"
        

          
  
